# Generated by Django 4.1.4 on 2025-04-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerification',
            new_name='EmailVerificationEvent',
        ),
    ]
