# Generated by Django 5.1.7 on 2025-05-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_students'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('course', 'email')},
        ),
    ]
